### Solution for Moving Average

In [1]:
def MovingAvg(lst,k): #k = window ,lst =list
    try:
        for i in range(len(lst)-k+1):
            summation = 0
            for j in range(k):
                summation += lst[i+j]
            print('y'+str(i),summation/k)
    except:
        print("please enter list of values as input")

In [2]:
MovingAvg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

y0 5.0
y1 4.666666666666667
y2 5.666666666666667
y3 6.666666666666667
y4 9.666666666666666
y5 28.666666666666668
y6 49.333333333333336
y7 72.66666666666667
y8 84.0
y9 93.33333333333333
y10 116.33333333333333


### Solution for Vandermonde

In [3]:
import numpy as np 

In [4]:
x = np.array([1, 2, 3, 5])
N = 3

In [5]:
def Uptopower(inputpcolumn , maxpower):
    newmatrix = np.asarray([x**(N-1-i) for i in range(N)])
    print(newmatrix.T)

In [6]:
Uptopower(x,N)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
